### ISSUE TITLE
Epic Code Challenge

### ISSUE THREAD

**Issue by richistron** [richistron/ghpwa#1]
Create a new React project (CRA preferred, but not required) and put the repo in your own github.com account so that we can see the code.

- [ ] Create an input field where a user can type in the name of a user on Github
- [ ] Create a submit/ok button that when clicked, brings the user's repo back. 
The is the API endpoint for retrieving user's repository 
`https://api.github.com/users/[uername]/repos`
- [ ] Display the following items on the page:
  - User's avatar
  - User's username
  - List of User's repository
  - link the repository to their respective URLs
  - Number of stars the repo has

Provide styling according to your creativity and make it look presentable. 
Bonus points: Provide UI error states for when the user is not found, API error, etc...
A react app is required, but feel free to use any additional libraries you like.
